# PATH
export PATH="/usr/bin:/bin:/usr/bin/X11:/usr/games:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin"
# $GHUB
export GHUB=$HOME/GitHub
# $GHUB/mine
export GHUBM=$GHUB/mine
# $GHUB/mine/websites
export WEB=$GHUBM/websites
# $GHUB/mine/websites/fusion809.github.io
export FGI=$WEB/fusion809.github.io
# $GHUB/mine/packaging
export PKG=$GHUBM/packaging
# $GHUB/mine/packaging/PKGBUILDs
export PK=$PKG/PKGBUILDs
# $GHUB/mine/scripts
export SCR=$GHUBM/scripts
# $GHUB/mine/scripts/opensuse-scripts
export OS=$SCR/opensuse-scripts
